backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "wyceny"
    label: "Wyceny"
    folder: "src/pages/wyceny"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "wyceny-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {labal: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}   
  - name: "specjalistyczne"
    label: "Specjalistyczne"
    folder: "src/pages/specjalistyczne"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "specjalistyczne-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {labal: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}      
  - name: "obsluga"
    label: "Obsluga"
    folder: "src/pages/obsluga"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "obsluga-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {labal: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}      
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/onas/index.md"
        label: "Onas"
        name: "onas"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "onas-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}  
      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kontakt-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/doradzctwo/index.md"
        label: "Doradzctwo"
        name: "doradzctwo"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "doradzctwo-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/wspolpraca/index.md"
        label: "Wspolpraca"
        name: "wspolpraca"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "wspolpraca-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}   
        