backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img

collections:
  - name: "projekt"
    label: "Projekt"
    folder: "src/pages/projekt"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "projekt-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {labal: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/onas/index.md"
        label: "Onas"
        name: "onas"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "onas-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}  
      - file: "src/pages/kontakt/index.md"
        label: "Kontakt"
        name: "kontakt"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "kontakt-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/wyceny/index.md"
        label: "Wyceny"
        name: "wyceny"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "wyceny-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/specjalistyczne/index.md"
        label: "Specjalistyczne"
        name: "specjalistyczne"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "specjalistyczne-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/obsluga/index.md"
        label: "Obsluga"
        name: "obsluga"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "obsluga-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/doradzctwo/index.md"
        label: "Doradzctwo"
        name: "doradzctwo"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "doradzctwo-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/wspolpraca/index.md"
        label: "Wspolpraca"
        name: "wspolpraca"
        fields:
        - {label: "Template Key", name: "templateKey", widget: "hidden", default: "wspolpraca-page"}
        - {label: "Title", name: "title", widget: "string"}
        - {labal: "Featured Image", name: "thumbnail", widget: "image"}
        - {label: "Description", name: "description", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}   
        